server:
  port: 8080
  servlet:
    context-path: /instagram

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/instagram"
    username: root
    password: 271204
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true